-- Crear tabla de comerciantes
CREATE TABLE Comerciantes (
    ComercianteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Departamento VARCHAR2(100) NOT NULL,
    Municipio VARCHAR2(100) NOT NULL,
    Telefono VARCHAR2(15),
    CorreoElectronico VARCHAR2(100),
    FechaRegistro DATE DEFAULT SYSDATE NOT NULL,
    Estado VARCHAR2(50) CHECK (
        Estado IN (
            'Registrado',
            'Activo',
            'Inactivo',
            'Suspendido',
            'Cancelado'
        )
    ),
    FechaActualizacion DATE,
    Usuario VARCHAR2(50)
);

-- Crear tabla de establecimientos
CREATE TABLE Establecimientos (
    EstablecimientoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ComercianteID NUMBER NOT NULL REFERENCES Comerciantes(ComercianteID),
    Nombre VARCHAR2(100) NOT NULL,
    Ingresos NUMBER(15, 2) DEFAULT 0 NOT NULL,
    NumeroEmpleados NUMBER DEFAULT 0 NOT NULL,
    FechaActualizacion DATE,
    Usuario VARCHAR2(50)
);